theme = "smol"
baseURL = "https://www.brodrigues.co/"
languageCode = "en-us"
title = "Econometrics and Free Software"
# Parameters
[params]
    subtitle = "Actually, it's mostly R."
    dateFmt = "2006/01/02"

# Header
[menu]
  [[menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/example"
        weight = 1 

    [[menu.footer]]
        name = "Mastodon"
        url = "https://example.com/@user"
        weight = 2 

    [[menu.footer]]
        name = "Imprint"
        url = "/imprint"
        weight = 3 
